# Generated by Django 5.2.7 on 2025-10-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='manual_description',
            field=models.TextField(blank=True, help_text="Description of what's included in the manual"),
        ),
        migrations.AddField(
            model_name='equipment',
            name='operating_manual',
            field=models.FileField(blank=True, help_text='Operating manual/user guide (PDF) - Available to customers after booking confirmation', null=True, upload_to='equipment_manuals/'),
        ),
    ]
