# Generated by Django 5.2.7 on 2025-11-02 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='equipment',
            name='equip_seller_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipment',
            name='equip_category_price_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipment',
            name='equip_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipment',
            name='equip_featured_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipment',
            name='equip_location_idx',
        ),
    ]
