# Generated by Django 5.2.7 on 2026-02-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_add_is_active_to_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='dimensions',
            field=models.CharField(blank=True, default='', help_text='LxWxH in cm', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='fuel_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='monthly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='weekly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
