# Generated by Django 5.2.7 on 2026-02-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_otp_signup_fields'),
        ('equipment', '0006_make_equipment_details_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['status'], name='equipment_e_status_fb8540_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['status', 'is_active'], name='equipment_e_status_21126e_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['category', 'status'], name='equipment_e_categor_149399_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['seller_company', 'status'], name='equipment_e_seller__a74cc6_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['featured', 'status'], name='equipment_e_feature_2bdf07_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['is_todays_deal', 'status'], name='equipment_e_is_toda_26ee38_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['is_new_listing', 'status'], name='equipment_e_is_new__df9f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['country', 'city', 'status'], name='equipment_e_country_6217cf_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['created_at'], name='equipment_e_created_ddb06c_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['-created_at'], name='equipment_e_created_75da64_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['daily_rate'], name='equipment_e_daily_r_06e16b_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentimage',
            index=models.Index(fields=['equipment', 'is_primary'], name='equipment_e_equipme_b72ee8_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentimage',
            index=models.Index(fields=['equipment', 'display_order'], name='equipment_e_equipme_6cd05a_idx'),
        ),
    ]
