# Generated by Django 5.2.7 on 2026-05-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='major_category',
            field=models.CharField(choices=[('construction', 'Construction'), ('electronics', 'Electronics & Home Appliances'), ('sports', 'Sports & Leisure'), ('home_goods', 'Home Goods'), ('cars_auto', 'Cars & Auto Products'), ('real_estate', 'Houses, Apartments & Dachas')], default='construction', help_text='The major front-page section this category belongs to', max_length=20),
        ),
    ]
