# Generated by Django 5.2.7 on 2025-10-21 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Collection name (e.g., 'Summer Projects', 'Next Month', 'Dream Equipment')", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False, help_text='Allow others to view this collection')),
                ('icon', models.CharField(blank=True, help_text="Icon name for mobile app (e.g., 'heart', 'star', 'bookmark')", max_length=50)),
                ('color', models.CharField(blank=True, help_text='Hex color code for collection (e.g., #FF6B35)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_collections', to='accounts.customerprofile')),
                ('equipment', models.ManyToManyField(blank=True, related_name='in_collections', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Personal notes about why they like this equipment')),
                ('preferred_rental_start', models.DateField(blank=True, help_text="When they'd like to rent this", null=True)),
                ('preferred_rental_duration', models.PositiveIntegerField(blank=True, help_text='Preferred rental duration in days', null=True)),
                ('notify_on_availability', models.BooleanField(default=False, help_text='Notify when equipment becomes available')),
                ('notify_on_price_drop', models.BooleanField(default=False, help_text='Notify when price drops')),
                ('notify_on_deals', models.BooleanField(default=True, help_text="Notify when there's a special deal")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='accounts.customerprofile')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='favorites_f_custome_fae226_idx'), models.Index(fields=['equipment', '-created_at'], name='favorites_f_equipme_492649_idx')],
                'unique_together': {('customer', 'equipment')},
            },
        ),
        migrations.CreateModel(
            name='RecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=1)),
                ('first_viewed_at', models.DateTimeField(auto_now_add=True)),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
                ('viewed_from', models.CharField(blank=True, help_text='Where they viewed from (search, category, featured, etc.)', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed', to='accounts.customerprofile')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Recently Viewed',
                'verbose_name_plural': 'Recently Viewed',
                'ordering': ['-last_viewed_at'],
                'indexes': [models.Index(fields=['customer', '-last_viewed_at'], name='favorites_r_custome_ab9268_idx')],
                'unique_together': {('customer', 'equipment')},
            },
        ),
    ]
