# Generated by Django 5.2.7 on 2025-10-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentaldocument',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='rentaldocument',
            name='requires_payment',
            field=models.BooleanField(default=False, help_text='Document only visible after payment (e.g., operating manual)'),
        ),
        migrations.AddField(
            model_name='rentaldocument',
            name='signature_data',
            field=models.JSONField(blank=True, default=dict, help_text='Digital signature information'),
        ),
        migrations.AddField(
            model_name='rentaldocument',
            name='visible_to_customer',
            field=models.BooleanField(default=True, help_text='Whether customer can see this document (e.g., internal notes should be False)'),
        ),
        migrations.AddField(
            model_name='rentalpayment',
            name='notes',
            field=models.TextField(blank=True, help_text="Additional notes about the payment (e.g., 'Cash collected on delivery by John')"),
        ),
        migrations.AddField(
            model_name='rentalpayment',
            name='receipt_file',
            field=models.FileField(blank=True, help_text='Payment receipt (uploaded by seller for cash on delivery or manual verification)', null=True, upload_to='payment_receipts/'),
        ),
        migrations.AddField(
            model_name='rentalpayment',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='Receipt/invoice number', max_length=50),
        ),
        migrations.AlterField(
            model_name='rentaldocument',
            name='document_type',
            field=models.CharField(choices=[('rental_agreement', 'Rental Agreement'), ('operating_manual', 'Operating Manual'), ('insurance_document', 'Insurance Document'), ('delivery_receipt', 'Delivery Receipt'), ('return_receipt', 'Return Receipt'), ('damage_report', 'Damage Report'), ('invoice', 'Invoice'), ('payment_receipt', 'Payment Receipt'), ('other', 'Other')], max_length=20),
        ),
    ]
