# Generated by Django 5.2.7 on 2025-11-02 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rental',
            name='rental_seller_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='rental',
            name='rental_customer_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='rental',
            name='rental_availability_idx',
        ),
        migrations.RemoveIndex(
            model_name='rental',
            name='rental_equipment_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='rental',
            name='rental_reference_idx',
        ),
    ]
