# Generated by Django 5.2.7 on 2025-12-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_remove_rental_rental_seller_status_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalpayment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cash', 'Cash'), ('cash_on_delivery', 'Cash on Delivery'), ('other', 'Other')], max_length=20),
        ),
    ]
