# Generated by Django 5.2.7 on 2025-12-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_alter_rentalpayment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='delivery_apartment_room',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rental',
            name='delivery_building',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rental',
            name='delivery_contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='rental',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='delivery_street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rental',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
