# Generated by Django 5.2.7 on 2026-02-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_otp_signup_fields'),
        ('equipment', '0007_add_performance_indexes'),
        ('rentals', '0007_rental_delivery_apartment_room_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalpayment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['status'], name='rentals_ren_status_fdfce4_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['customer', 'status'], name='rentals_ren_custome_a8e224_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['seller', 'status'], name='rentals_ren_seller__ad9525_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['equipment', 'status'], name='rentals_ren_equipme_da97ef_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['start_date', 'end_date'], name='rentals_ren_start_d_9e0d01_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['equipment', 'start_date', 'end_date'], name='rentals_ren_equipme_f33cdd_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['rental_reference'], name='rentals_ren_rental__f4967d_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['created_at'], name='rentals_ren_created_e28652_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['-created_at'], name='rentals_ren_created_3a2c6c_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['seller', 'created_at'], name='rentals_ren_seller__d1d16d_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['customer', 'created_at'], name='rentals_ren_custome_e3936c_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalpayment',
            index=models.Index(fields=['rental', 'payment_status'], name='rentals_ren_rental__a6702b_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalpayment',
            index=models.Index(fields=['payment_status'], name='rentals_ren_payment_a4e109_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalpayment',
            index=models.Index(fields=['gateway_reference'], name='rentals_ren_gateway_0c3e26_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalpayment',
            index=models.Index(fields=['created_at'], name='rentals_ren_created_de7368_idx'),
        ),
    ]
