# Generated by Django 5.2.7 on 2026-03-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_otp_signup_fields'),
        ('equipment', '0007_add_performance_indexes'),
        ('rentals', '0008_add_performance_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['customer', '-end_date'], name='rentals_ren_custome_7d7797_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalsale',
            index=models.Index(fields=['sale_date'], name='rentals_ren_sale_da_e6ae43_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalsale',
            index=models.Index(fields=['-sale_date'], name='rentals_ren_sale_da_b71d33_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalsale',
            index=models.Index(fields=['equipment', '-sale_date'], name='rentals_ren_equipme_285dcd_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalsale',
            index=models.Index(fields=['seller', 'payout_status'], name='rentals_ren_seller__91193e_idx'),
        ),
    ]
