# Generated by Django 5.2.7 on 2025-12-09 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='employee_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Home, Office, Warehouse', max_length=50)),
                ('apartment_room', models.CharField(blank=True, help_text='Apartment, Suite, or Room number', max_length=50)),
                ('building', models.CharField(blank=True, help_text='Building name or number', max_length=100)),
                ('street_landmark', models.CharField(help_text='Street name and nearby landmark', max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('contact_number', models.CharField(help_text='Contact number for this location', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Delivery Addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
