# Generated by Django 5.2.7 on 2025-12-31 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_otp_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='email',
            field=models.EmailField(blank=True, default='', help_text="Email for signup OTPs when user doesn't exist yet", max_length=254),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='registration_data',
            field=models.JSONField(blank=True, help_text='Pending registration data for signup OTPs', null=True),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('signup', 'Signup'), ('verify_email', 'Email Verification')], default='login', max_length=20),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
