# Generated by Django 5.2.7 on 2026-05-29 08:25

from django.db import migrations


def set_default_city_dubai(apps, schema_editor):
    CustomerProfile = apps.get_model('accounts', 'CustomerProfile')
    CustomerProfile.objects.filter(city__isnull=True).update(city='DXB')
    CustomerProfile.objects.filter(city='').update(city='DXB')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_otp_signup_fields'),
    ]

    operations = [
        migrations.RunPython(set_default_city_dubai, migrations.RunPython.noop),
    ]
