"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-1@$18-=0*)lp8y)w)ris9vu)n5#%$jcptab8m+r5iceu+j@@@l')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    'localhost', 
    '127.0.0.1', 
    '[::1]',
    '169.254.130.4',  # Azure internal health check
    'sellerdashtezrent.netlify.app',  # Your Netlify frontend
    'tezrentapibackend-bsatbme3eqfkfnc3.canadacentral-01.azurewebsites.net',  # Azure backend
    '*',  # Allow all hosts (for Azure's internal routing)
]

# Add deployment hosts from environment variable
if 'ALLOWED_HOSTS' in os.environ:
    ALLOWED_HOSTS.extend(os.environ.get('ALLOWED_HOSTS').split(','))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'storages',  # Azure Blob Storage
    # Add your apps here
    'accounts.apps.AccountsConfig',
    'equipment.apps.EquipmentConfig',
    'rentals.apps.RentalsConfig',
    'payments.apps.PaymentsConfig',
    'crm.apps.CrmConfig',
    'notifications.apps.NotificationsConfig',
    'favorites.apps.FavoritesConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Add this near the top
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add for static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import dj_database_url

# PostgreSQL Configuration - Using Render PostgreSQL
# Use DATABASE_URL environment variable if available, otherwise use Render database
DATABASE_URL = os.getenv('DATABASE_URL', 'postgresql://derby:TqPq4C0jrZAGdrCXZoAlI858mBDPJLKA@dpg-d5oq3sggjchc73ajqa10-a.oregon-postgres.render.com/tezrent')

if DATABASE_URL:
    # Production - uses DATABASE_URL connection string (Render PostgreSQL)
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,  # Connection pooling (10 minutes)
            conn_health_checks=True,  # Verify connections are alive
        )
    }
else:
    # Local development - SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# This setting informs Django of the URI path from which your static files will be served
STATIC_URL = '/static/'

# Tell Django to copy static assets into a path called `staticfiles` (this is specific to Render)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Enable the WhiteNoise storage backend in production
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'accounts.User'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Simple JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# CORS settings
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'https://sellerdashtezrent.netlify.app',  # Your Netlify frontend
    'https://tezrentapibackend-bsatbme3eqfkfnc3.canadacentral-01.azurewebsites.net',  # Azure backend
    'https://tezrent-api.onrender.com',  # Render backend
]

# Allow requests from mobile apps (React Native, Flutter, etc.)
# Mobile apps don't send Origin headers, so we need to allow null origins
CORS_ALLOW_ALL_ORIGINS = True  # Allow all origins for mobile app support

CORS_ALLOW_CREDENTIALS = True

# Allow all HTTP methods
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Allow common headers from mobile apps
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# CSRF settings for React frontend
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'https://sellerdashtezrent.netlify.app',  # Your Netlify frontend
    'https://tezrentapibackend-bsatbme3eqfkfnc3.canadacentral-01.azurewebsites.net',  # Azure backend
]

# Email settings - Gmail SMTP with custom backend for macOS SSL fix
EMAIL_BACKEND = 'accounts.email_backend.CustomEmailBackend'  # Custom backend to bypass SSL verification
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_FROM = 'dmatderby@gmail.com'
EMAIL_HOST_USER = 'dmatderby@gmail.com'
EMAIL_HOST_PASSWORD = 'fneo xmrd qego epxy'
EMAIL_PORT = 465  # Using SSL port
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
DEFAULT_FROM_EMAIL = 'TezRent <dmatderby@gmail.com>'

# Password reset timeout (4 hours = 14400 seconds)
PASSWORD_RESET_TIMEOUT = 14400

# reCAPTCHA configuration
RECAPTCHA_PUBLIC_KEY = '6LddA3kgAAAAAPf1mAJmEc7Ku0cssbD5QMha09NT'
RECAPTCHA_PRIVATE_KEY = '6LddA3kgAAAAAJY-2-Q0J3QX83DFJwFR1hXqmN8q'
SILENCED_SYSTEM_CHECKS = ['captcha.recaptcha_test_key_error']

# Ziina Payment Gateway Configuration
# Get API key from: https://dashboard.ziina.com/developers
ZIINA_API_KEY = os.environ.get('ZIINA_API_KEY', '9kmWHJucbKTfVeYww1UfHs2CeMGrEJzRPOS+AfeZ56FiEZGJnUgGafecDGhjoymb')
ZIINA_TEST_MODE = os.environ.get('ZIINA_TEST_MODE', 'True') == 'True'  # Set to False in production

# Media files configuration
# Use Azure Blob Storage in production, local filesystem in development
if os.getenv('AZURE_STORAGE_ACCOUNT_NAME'):
    # Azure Blob Storage configuration (production)
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.azure_storage.AzureStorage",
            "OPTIONS": {
                "account_name": os.getenv('AZURE_STORAGE_ACCOUNT_NAME'),
                "account_key": os.getenv('AZURE_STORAGE_ACCOUNT_KEY'),
                "azure_container": os.getenv('AZURE_STORAGE_CONTAINER_NAME', 'media'),
                "overwrite_files": False,
                "cache_control": "public,max-age=31536000",
            },
        },
    }
    AZURE_ACCOUNT_NAME = os.getenv('AZURE_STORAGE_ACCOUNT_NAME')
    AZURE_CUSTOM_DOMAIN = f'{AZURE_ACCOUNT_NAME}.blob.core.windows.net'
    AZURE_CONTAINER = os.getenv('AZURE_STORAGE_CONTAINER_NAME', 'media')
    MEDIA_URL = f'https://{AZURE_CUSTOM_DOMAIN}/{AZURE_CONTAINER}/'
else:
    # Local development - use filesystem
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
    MEDIA_URL = '/media/'